package com.vozmediano.mvc.model.entity;
// Generated 25 Dec 2024, 17:20:27 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonIgnore;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;

/**
 * Teams generated by hbm2java
 */
@Entity
@Table(name = "teams", catalog = "nba")
public class Teams implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String name;
	private String city;
	private String conference;
	private String division;
	private Set<Matches> matchesesForVisitorTeam = new HashSet<Matches>(0);
	private Set<Players> playerses = new HashSet<Players>(0);
	private Set<Matches> matchesesForLocalTeam = new HashSet<Matches>(0);

	public Teams() {
	}

	public Teams(String name) {
		this.name = name;
	}

	public Teams(String name, String city, String conference, String division, Set<Matches> matchesesForVisitorTeam,
			Set<Players> playerses, Set<Matches> matchesesForLocalTeam) {
		this.name = name;
		this.city = city;
		this.conference = conference;
		this.division = division;
		this.matchesesForVisitorTeam = matchesesForVisitorTeam;
		this.playerses = playerses;
		this.matchesesForLocalTeam = matchesesForLocalTeam;
	}

	@Id

	@Column(name = "Name", unique = true, nullable = false, length = 20)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "City", length = 20)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "Conference", length = 4)
	public String getConference() {
		return this.conference;
	}

	public void setConference(String conference) {
		this.conference = conference;
	}

	@Column(name = "Division", length = 9)
	public String getDivision() {
		return this.division;
	}

	public void setDivision(String division) {
		this.division = division;
	}
	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "teamsByVisitorTeam")
	public Set<Matches> getMatchesesForVisitorTeam() {
		return this.matchesesForVisitorTeam;
	}

	public void setMatchesesForVisitorTeam(Set<Matches> matchesesForVisitorTeam) {
		this.matchesesForVisitorTeam = matchesesForVisitorTeam;
	}
	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "teams")
	public Set<Players> getPlayerses() {
		return this.playerses;
	}

	public void setPlayerses(Set<Players> playerses) {
		this.playerses = playerses;
	}
	
	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "teamsByLocalTeam")
	public Set<Matches> getMatchesesForLocalTeam() {
		return this.matchesesForLocalTeam;
	}

	public void setMatchesesForLocalTeam(Set<Matches> matchesesForLocalTeam) {
		this.matchesesForLocalTeam = matchesesForLocalTeam;
	}

}
