package com.xavi.backend.nba.model.entity;
// Generated 5 dic 2023 9:24:52 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;

/**
 * Players generated by hbm2java
 */
@Entity
@Table(name = "players", catalog = "nba")
public class Players implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int code;
	private Teams teams;
	private String name;
	private String origin;
	private String height;
	private Integer weight;
	private String position;
	private Integer salary;
	private Set<Stats> statses = new HashSet<>(0);

	public Players() {
	}

	public Players(int code) {
		this.code = code;
	}

	public Players(int code, Teams teams, String name, String origin, String height, Integer weight, String position,
			Integer salary, Set<Stats> statses) {
		this.code = code;
		this.teams = teams;
		this.name = name;
		this.origin = origin;
		this.height = height;
		this.weight = weight;
		this.position = position;
		this.salary = salary;
		this.statses = statses;
	}

	@Id

	@Column(name = "code", unique = true, nullable = false)
	public int getCode() {
		return this.code;
	}

	public void setCode(int code) {
		this.code = code;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Team_name")
	@JsonIgnoreProperties({"playerses","hiberanteLazyInitializer"})
	public Teams getTeams() {
		return this.teams;
	}

	public void setTeams(Teams teams) {
		this.teams = teams;
	}

	@Column(name = "Name", length = 30)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "Origin", length = 20)
	public String getOrigin() {
		return this.origin;
	}

	public void setOrigin(String origin) {
		this.origin = origin;
	}

	@Column(name = "Height", length = 4)
	public String getHeight() {
		return this.height;
	}

	public void setHeight(String height) {
		this.height = height;
	}

	@Column(name = "Weight")
	public Integer getWeight() {
		return this.weight;
	}

	public void setWeight(Integer weight) {
		this.weight = weight;
	}

	@Column(name = "Position", length = 5)
	public String getPosition() {
		return this.position;
	}

	public void setPosition(String position) {
		this.position = position;
	}

	@Column(name = "Salary")
	public Integer getSalary() {
		return this.salary;
	}

	public void setSalary(Integer salary) {
		this.salary = salary;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "players")
	@JsonIgnore
	public Set<Stats> getStatses() {
		return this.statses;
	}

	public void setStatses(Set<Stats> statses) {
		this.statses = statses;
	}

}
